### ISSUE TITLE
 Open Remote Window appears strongly highlighted

### ISSUE THREAD

**Issue by wesbos** [wesbos/cobalt2-vscode#220]
Moved from https://github.com/wesbos/cobalt2/issues/181

![image](https://user-images.githubusercontent.com/176013/217018024-ce479a98-8455-46c0-94c0-b7749d01ceb8.png)

@sambecker 

Not sure if this is intended behavior from VS Code or from the theme itself, but the effect is that it seems like some action needs to be taken.

**Comment by wesbos** [comment]
@sambecker I'm not sure how to get this icon to show up. What is it for? Remote connections?

**Comment by sambecker** [comment]
I have no idea. It only showed up for me after updating to the January 2023 (`1.75.0`) version of VS Code.

When I hover over it, it says: `Open a Remote Window`. It's a feature I don't think I've ever used.

**Comment by Asjas** [comment]
@wesbos It's for WSL on Windows. 🙂 

![Untitled](https://user-images.githubusercontent.com/3828967/217026737-eda07b4a-3a8c-427f-ad9b-5186b95e165d.png)

Mine looks green because I use [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) to change the color of all the major UI parts in VSC, but it's that Yellow by default.

If I click on it this pop-up shows.

![Untitled1](https://user-images.githubusercontent.com/3828967/217027106-6714a3e5-7a4b-46cc-9987-7c4b8bbd8671.png)

**Comment by Sanqui** [comment]
It's not just WSL, I have this icon too and it does appear a bit distracting (in addition the hover state looks a bit wrong). Perhaps try installing the `Remote - SSH` extension.

**Comment by wesbos** [comment]
I see it now too. Not sure how VS Code decides which color it is. The hover color is weird too 

<img width="1065" alt="Screenshot 2023-02-13 at 11 12 01 AM" src="https://user-images.githubusercontent.com/176013/218511193-5424afcd-b0e6-439b-8bdb-031baee06de9.png">

**Comment by wesbos** [comment]
Some more info from  Chris Dias. I'll ask if he knows anything about it

https://twitter.com/chrisdias/status/1622763233378721792

**Comment by StephenBuley** [comment]
Hey Wes, I'd love to take a shot at this if no one else is working on it. I just completed my own VSCode theme [Mando Dark](https://github.com/StephenBuley/mando-dark) and am trying to get more experience contributing to projects that aren't my own.

**Comment by palashmon** [comment]
Fixed in PR #225
