### ISSUE TITLE
find & replace highlight color hard to see at night

### ISSUE THREAD

**Issue by blacktop** [wesbos/cobalt2-vscode#41]
![screen shot 2017-09-17 at 9 52 55 am](https://user-images.githubusercontent.com/6118188/30522515-72b39086-9b8e-11e7-82fc-99f3179b0a82.png)

This morning it looks ok, but late at night with **f.lux** on, I couldn't see what it was highlighting at all, it all looked orange.

NOTE: I also use a smaller font size than you do.

Thanks btw this is a truly great theme.

**Comment by wesbos** [comment]
I'm not sure which colour would work instead because VS code doesn't allow for borders. Almost I've tried many different colours but everything seems to get lost on some sort of syntax. 

The orange is the best I've found after many hours - feel free to overwrite this in your own settings file and let me know if you find a better colour.

**Comment by blacktop** [comment]
Thank you, I greatly appreciate your time and effort.
